"""inclusao de campo respondido na tabela contatos

Revision ID: 0441e4ec62b0
Revises: 19714c4702eb
Create Date: 2025-08-10 11:30:23.416832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0441e4ec62b0'
down_revision = '19714c4702eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('answered')

    # ### end Alembic commands ###
