"""inclusao de campo response na tabela contato

Revision ID: 6c22362f2331
Revises: 9b92fc8f2bfc
Create Date: 2025-08-01 22:29:01.687516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c22362f2331'
down_revision = '9b92fc8f2bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('response')

    # ### end Alembic commands ###
